FROM alpine
 
# shows secret from default secret location:
 
# RUN --mount=type=secret,id=mysecret cat /run/secrets/mysecret
# install ssh client and git
RUN apk add --no-cache openssh-client git
RUN echo "building"

